  CREATE TABLE EMPS 
   (EMP_ID NUMBER(38) PRIMARY KEY, 
	NAME VARCHAR2(100 CHAR) NOT NULL, 
	EMP_TYPE VARCHAR2(20 CHAR) NOT NULL DEFAULT 'SALARIED', 
	START_DATE DATE, 
	END_DATE DATE, 
	BLA_TSZ TIMESTAMP (6) WITH TIME ZONE, 
	DUMMY_TS TIMESTAMP (6), 
	LIFE_HISTORY CLOB
   ) ;

  ALTER TABLE EMPS ADD CONSTRAINT EMP_TYPE_CK CHECK ( emp_type IN ('SALARIED','CONTRACTOR')) ENABLE;
  ALTER TABLE EMPS ADD CONSTRAINT EMP_NAME_UK UNIQUE (NAME) ENABLE;
