begin deploy.create_table(table_name => 'events', table_ddl => q'[
create table #NAME#
  (event_id        integer generated by default on null as identity not null
  ,host_id         integer not null
  ,event_type      varchar2 (100 char) not null
  ,title           varchar2 (100 char) not null
  ,description     varchar2 (4000)
  ,venue_id        integer
  ,start_dt        date not null
  ,end_dt          date
  ,repeat          varchar2 (100 char) /* DAILY, WEEKLY, MONTHLY, ANNUALLY */
  ,repeat_interval number default on null 1
  ,repeat_until    date
  ,deleted_y       varchar2(1)
  )]');
end;
/

begin deploy.add_constraint(constraint_name => 'events_pk', constraint_ddl => q'[alter table events add constraint #NAME# primary key ( event_id )]'); end;
/
begin deploy.add_constraint(constraint_name => 'event_name_uk', constraint_ddl => q'[alter table events add constraint #NAME# unique ( title )]'); end;
/
begin deploy.add_constraint(constraint_name => 'event_date_range_ck', constraint_ddl => q'[alter table events add constraint #NAME# check ( start_dt <= end_dt )]'); end;
/
begin deploy.add_constraint(constraint_name => 'event_deleted_ck', constraint_ddl => q'[alter table events add constraint #NAME# check ( deleted_y = 'Y' )]'); end;
/

begin deploy.add_constraint(constraint_name => 'event_type_fk', constraint_ddl => q'[alter table events add constraint #NAME# foreign key ( event_type ) references event_types ( event_type )]'); end;
/
begin deploy.add_constraint(constraint_name => 'event_host_fk', constraint_ddl => q'[alter table events add constraint #NAME# foreign key ( host_id ) references hosts ( host_id )]'); end;
/
begin deploy.add_constraint(constraint_name => 'event_venue_fk', constraint_ddl => q'[alter table events add constraint #NAME# foreign key ( venue_id ) references venues ( venue_id )]'); end;
/

