begin deploy.create_table(table_name => 'venues', table_ddl => q'[
create table #name#
  (venue_id     integer generated by default on null as identity not null
  ,name         varchar2 (500 char) not null
  ,map_position varchar2 (100 char)
  ,deleted_y    varchar2(1)
  )]', vpd => true);
end;
/

begin deploy.add_constraint(constraint_name => 'venue_pk', constraint_ddl => q'[alter table venues add constraint #name# primary key ( venue_id )]'); end;
/
begin deploy.add_constraint(constraint_name => 'venue_name_uk', constraint_ddl => q'[alter table venues add constraint #name# unique ( name )]'); end;
/
begin deploy.add_constraint(constraint_name => 'venue_deleted_ck', constraint_ddl => q'[alter table venues add constraint #name# check ( deleted_y = 'Y' )]'); end;
/
