begin deploy.create_table(table_name => 'venues', table_ddl => q'[
create table #name#
  (venue_id        integer generated by default on null as identity not null
  ,name            varchar2 (500 char)
  ,map_position    varchar2 (100 char)
  )]');
end;
/

begin deploy.add_constraint(constraint_name => 'venue_pk', constraint_ddl => q'[alter table venues add constraint #NAME# primary key ( venue_id )]'); end;
/
begin deploy.add_constraint(constraint_name => 'venue_name_uk', constraint_ddl => q'[alter table venues add constraint #NAME# unique ( name )]'); end;
/
